#!/bin/bash

usage() {
	echo "Submodule updater"
	echo "Usage: ./scripts/update <branch-name>"
	echo "    examples"
	echo "    - ./scripts/update dev-george"
	echo "    - ./scripts/update dev-andy"
}

doAction() {
	set -xe
	branch=$1
	tmp="tmp"
	git submodule foreach "git add ."
	git submodule foreach "git commit -m 'Synchronizing all submodules' || echo 'already upto date'"
	git submodule foreach "git checkout $branch || git checkout -b $branch || echo 'already in branch $branch'"
	git submodule foreach "git commit -m 'Synchronizing all submodules' || echo 'already upto date'"
	git submodule foreach "git branch --delete $tmp || echo 'preparing $tmp branch'"
	git submodule foreach "git push origin $branch"
	git submodule update --init
	git submodule foreach "git checkout -b $tmp || git checkout $tmp"
	git submodule foreach "git checkout $branch"
	git submodule foreach "git merge $tmp"
	git submodule foreach "git branch --delete $tmp"
	git add .
	git commit -m "Updated submodules"
}

main() {
	branch=$1;
	if [[ -z "$branch" ]]; then
		usage
	else
		doAction "$branch"
	fi
}

main $1;